### ISSUE TITLE
Read quality histogram harcoded xlims are not appropiated for all datasets

### ISSUE THREAD

**Issue by waltergallegog** [epi2me-labs/wf-human-snp#6]
Hello,
Using my dataset, the histogram plot for read quality is empty.
This is because the xlim used is too restrictive, and the quality on my data is lower than 85.

https://github.com/epi2me-labs/wf-human-snp/blob/2129eee024f162d6198278738243c80a8c8001d0/bin/report.py#L45

When looking at the html report, it is not obvious to the user that the quality data is present, but just not visible in the plot.
It is also not possible to zoom out past the 85, 100 limit, or to seek the data moving to the left.

Maybe it is better choose the limits according to the distribution, or to remove the limit altogether?

Thanks and BR.

**Comment by SamStudio8** [comment]
Hi @waltergallegog, these limits were chosen as sensible limits for the vast majority of datasets. If your data is falling outside of these bounds, I suspect you have wider issues that might need to be addressed before interpreting the report. We are sorry that the report is however confusing in this case. We do have plans to change how we build some of the plots and will take your feedback into consideration for how we can improve our reports in future.

**Comment by waltergallegog** [comment]
Hi @SamStudio8. Thanks for the info and advice, I will check on that. I may have chosen the wrong model when using clair3.

**Comment by waltergallegog** [comment]
Hi @SamStudio8 , just FYI you were right, there was an issue on my side. I have rerun and now I get quality values between 80 and 100.
The changes I did were:
 - appropriate clair3 model for my dataset.
 - aligner. I was using the results obtained from LRA, but according to https://github.com/HKU-BAL/Clair3/issues/102 it is better to use minmap2
